BYTE_TYPE = "byte"
SHORT_TYPE = "short"
INT_TYPE = "int"
LONG_TYPE = "long"
FLOAT_TYPE = "float"
DOUBLE_TYPE = "double"
PRIMARY_ARITHMETIC_TYPES = [BYTE_TYPE, SHORT_TYPE, INT_TYPE, LONG_TYPE, FLOAT_TYPE, DOUBLE_TYPE]

CHAR_TYPE = "char"
STRING_TYPE = "String"

PRIMARY_TEXT_TYPES = [CHAR_TYPE, STRING_TYPE]
